# Generated by Django 2.2.16 on 2020-12-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='attachment',
            field=models.FileField(blank=True, upload_to='files/', verbose_name='简历附件'),
        ),
        migrations.AddField(
            model_name='resume',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='简历照片'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='degree',
            field=models.CharField(blank=True, choices=[('本科', '本科'), ('硕士', '硕士'), ('博士', '博士')], max_length=135, verbose_name='学历'),
        ),
    ]
